# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'profile_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15profile_service.proto\x12\x0eprofileservice\"!\n\x0eProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x84\x01\n\x0fProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x05\x12\x0b\n\x03\x62io\x18\x07 \x01(\t2_\n\x0eProfileService\x12M\n\nGetProfile\x12\x1e.profileservice.ProfileRequest\x1a\x1f.profileservice.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILEREQUEST']._serialized_start=41
  _globals['_PROFILEREQUEST']._serialized_end=74
  _globals['_PROFILERESPONSE']._serialized_start=77
  _globals['_PROFILERESPONSE']._serialized_end=209
  _globals['_PROFILESERVICE']._serialized_start=211
  _globals['_PROFILESERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
