# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedido.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpedido.proto\"\xa3\x01\n\x06Pedido\x12\x11\n\tid_pedido\x18\x01 \x01(\x05\x12\x16\n\x0e\x63liente_nombre\x18\x02 \x01(\t\x12\x15\n\rcliente_email\x18\x03 \x01(\t\x12\x1a\n\x05items\x18\x04 \x03(\x0b\x32\x0b.ItemPedido\x12\r\n\x05total\x18\x05 \x01(\x01\x12\r\n\x05\x66\x65\x63ha\x18\x06 \x01(\t\x12\x1d\n\x06\x65stado\x18\x07 \x01(\x0e\x32\r.EstadoPedido\"e\n\nItemPedido\x12\x13\n\x0bid_producto\x18\x01 \x01(\x05\x12\x17\n\x0fnombre_producto\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\x12\x17\n\x0fprecio_unitario\x18\x04 \x01(\x01*X\n\x0c\x45stadoPedido\x12\r\n\tPENDIENTE\x10\x00\x12\x0e\n\nCONFIRMADO\x10\x01\x12\x0b\n\x07\x45NVIADO\x10\x02\x12\r\n\tENTREGADO\x10\x03\x12\r\n\tCANCELADO\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedido_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ESTADOPEDIDO._serialized_start=285
  _ESTADOPEDIDO._serialized_end=373
  _PEDIDO._serialized_start=17
  _PEDIDO._serialized_end=180
  _ITEMPEDIDO._serialized_start=182
  _ITEMPEDIDO._serialized_end=283
# @@protoc_insertion_point(module_scope)
