# Scraped Page Titles
# Generated by BeautifulSoup scraper

page_titles = [
    ('https://www.python.org', 'Welcome to Python.org'),
    ('https://www.github.com', 'GitHub · Build and ship software on a single, collaborative platform · GitHub'),
    ('https://www.stackoverflow.com', 'Error: 403 Client Error: Forbidden for url: https://stackoverflow.com/'),
]

if __name__ == '__main__':
    for url, title in page_titles:
        print(f'{url}: {title}')
