# MySQL Query Results (Simulated)
# This file was generated by the MySQL SELECT query script
# Columns: ['id', 'name', 'email', 'created_date']

results = [
    (1, 'John Doe', 'john@example.com', '2023-01-15'),
    (2, 'Jane Smith', 'jane@example.com', '2023-02-20'),
    (3, 'Bob Johnson', 'bob@example.com', '2023-03-10'),
]

# End of results
