from fastapi import FastAPI
import random
import string

app = FastAPI()

def generate_random_filename():
    """Generates a random filename with a .py extension."""
    random_name = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
    return f"{random_name}.py"

@app.post("/")
async def create_file_endpoint():
    """FastAPI endpoint that creates a file with random name."""
    filename = generate_random_filename()
    with open(filename, 'w') as f:
        f.write("# This is a randomly named Python file generated by the FastAPI endpoint.\n")
    return {"message": f"File {filename} created successfully!"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)