import requests
from bs4 import BeautifulSoup
import random
import string

def generate_random_filename():
    """Generate a random filename with .py extension"""
    random_name = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    return f"{random_name}.py"

def scrape_page_titles(urls):
    """
    Scrape page titles from a list of URLs
    
    Args:
        urls (list): List of URLs to scrape titles from
    
    Returns:
        list: List of tuples containing (url, title)
    """
    results = []
    
    for url in urls:
        try:
            # Add protocol if missing
            if not url.startswith(('http://', 'https://')):
                url = 'https://' + url
            
            # Make request to the URL
            response = requests.get(url, timeout=10)
            response.raise_for_status()  # Raise an exception for bad status codes
            
            # Parse the HTML content
            soup = BeautifulSoup(response.content, 'html.parser')
            
            # Find the title tag
            title_tag = soup.find('title')
            title = title_tag.get_text().strip() if title_tag else "No title found"
            
            results.append((url, title))
            print(f"Scraped: {url} -> {title}")
            
        except requests.RequestException as e:
            print(f"Error fetching {url}: {e}")
            results.append((url, f"Error: {e}"))
        except Exception as e:
            print(f"Error parsing {url}: {e}")
            results.append((url, f"Error: {e}"))
    
    return results

def main():
    # Example URLs to scrape
    urls = [
        "https://www.python.org",
        "https://www.github.com",
        "https://www.stackoverflow.com"
    ]
    
    print("Starting to scrape page titles...")
    results = scrape_page_titles(urls)
    
    # Save results to a file
    output_filename = generate_random_filename()
    
    with open(output_filename, 'w', encoding='utf-8') as f:
        f.write("# Scraped Page Titles\n")
        f.write("# Generated by BeautifulSoup scraper\n\n")
        f.write("page_titles = [\n")
        for url, title in results:
            f.write(f"    ('{url}', '{title}'),\n")
        f.write("]\n")
        
        f.write("\nif __name__ == '__main__':\n")
        f.write("    for url, title in page_titles:\n")
        f.write("        print(f'{url}: {title}')\n")
    
    print(f"\nResults saved to {output_filename}")

if __name__ == "__main__":
    main()