import random
import string
from selenium import webdriver
from selenium.webdriver.common.by import By

# Initialize the Chrome WebDriver
driver = webdriver.Chrome()

try:
    # Navigate to Google
    driver.get("https://www.google.com")

    # Generate a random filename
    random_filename = ''.join(random.choices(string.ascii_letters + string.digits, k=10)) + ".py"

    # Save the current URL to the randomly named file
    with open(random_filename, 'w') as f:
        f.write(f"# This file was generated by navigating to: {driver.current_url}\n")
        f.write("# Selenium Test Script\n")

    print(f"Selenium test executed and saved to {random_filename}")

finally:
    # Close the browser
    driver.quit()
