import random
import string
import os

def generate_random_filename():
    """Generate a random filename with .py extension"""
    random_string = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    return f"{random_string}.py"

def simulate_mysql_select():
    """
    Simulated function to demonstrate MySQL SELECT query execution
    In a real scenario, this would connect to an actual MySQL database
    """
    print("Simulating MySQL SELECT query execution...")
    
    # Simulated query results (in a real scenario, these would come from the database)
    column_names = ['id', 'name', 'email', 'created_date']
    records = [
        (1, 'John Doe', 'john@example.com', '2023-01-15'),
        (2, 'Jane Smith', 'jane@example.com', '2023-02-20'),
        (3, 'Bob Johnson', 'bob@example.com', '2023-03-10')
    ]
    
    print(f"Column names: {column_names}")
    print("Records:")
    for row in records:
        print(row)
        
    # Generate a random filename
    random_filename = generate_random_filename()
    
    # Write the simulated results to the randomly named Python file
    with open(random_filename, 'w') as f:
        f.write("# MySQL Query Results (Simulated)\n")
        f.write("# This file was generated by the MySQL SELECT query script\n")
        f.write(f"# Columns: {column_names}\n\n")
        f.write("results = [\n")
        for row in records:
            f.write(f"    {row},\n")
        f.write("]\n\n")
        f.write("# End of results\n")
        
    print(f"Results saved to {random_filename}")
    return random_filename

if __name__ == "__main__":
    filename = simulate_mysql_select()
    print(f"\nCreated file: {filename}")
    
    # List the files in the current directory to confirm the random file was created
    print("\nFiles in current directory:")
    for file in os.listdir('.'):
        if file.endswith('.py') and file != 'simulated_mysql_select.py':
            print(f"  - {file}")