---
- name: Копирование файла
  hosts: all
  become: yes
  tasks:
    - name: Копировать файл hosts
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /tmp/hosts.backup
        mode: '0644'